### PR TITLE
Added functionality to delete database

### PR DESCRIPTION
**Pull request by MYaseenAKAKhan**
Added functionality to delete database in both place i.e. added button in qml and logic in class file.

### CODE REVIEW

**Comment by timwindsor** [comment]
Thanks! I think this is small enough that we can accept it without requiring a contributor agreement. It looks like you are using some of the projects, so maybe you'd be interested in doing more contributions in the future? For those who make larger or more regular contributions, we have them sign the standard Apache Contributor License Agreement, and include them in our list of [official contributors](http://blackberry.github.io/approvedSignatories.html). We'd certainly love to have you included if you are interested. Thanks again for submitting this.

**Comment by MYaseenAKAKhan** [comment]
Thanks for your kind reply and proposal, I am interested in signing the Agreement, Please guide me further

**Comment by timwindsor** [comment]
Sure. Fill out this [document](http://www.blackberry.com/legal/pdfs/webworks/Research_In_Motion_Limited_ICLA_021811_cl.pdf) and email it in to github@blackberry.com. Optionally, we also include your city on a map of contributors if you are okay with that. Thanks

**Comment by MYaseenAKAKhan** [comment]
Thanks, I will sign and mail it. By the way if you don't here is some suggestion there is a typo in a document, Read first paragraph you will find it there i.e. "Please read his document" here "T" is missing.
I think email address should also be updated from "github@rim.com" to github@blackberry.com.

**Comment by timwindsor** [comment]
Thanks - yes it's on my list to get this document updated.

**Comment by MYaseenAKAKhan** [comment]
Hello Tim,
I have sent documents via email but didn't received any kind of response yet. Does it takes time

**Comment by timwindsor** [comment]
I got them but haven't processed it yet. I will be posting your name to the official contributor list shortly.

**Pull request merged**
